"""empty message

Revision ID: 01e593c210a7
Revises: 07c2f9abb4a0
Create Date: 2025-05-12 02:48:48.760828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e593c210a7'
down_revision = '07c2f9abb4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offres_financieres', sa.Column('unite_monetaire', sa.Boolean(), nullable=True))
    op.add_column('offres_financieres', sa.Column('taux_echange', sa.Float(), nullable=True))
    op.add_column('offres_financieres', sa.Column('prix_unitaire_mru', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offres_financieres', 'prix_unitaire_mru')
    op.drop_column('offres_financieres', 'taux_echange')
    op.drop_column('offres_financieres', 'unite_monetaire')
    # ### end Alembic commands ###
