"""empty message

Revision ID: 07c2f9abb4a0
Revises: 7798cb67b6a4
Create Date: 2025-05-11 16:32:41.982724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c2f9abb4a0'
down_revision = '7798cb67b6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offres_techniques', sa.Column('exclure', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offres_techniques', 'exclure')
    # ### end Alembic commands ###
