"""Add email field to Fournisseur

Revision ID: 27979ef41132
Revises: e89a32387ae8
Create Date: 2025-04-24 16:29:54.368024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27979ef41132'
down_revision = 'e89a32387ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fournisseurs', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fournisseurs', 'email')
    # ### end Alembic commands ###
