"""empty message

Revision ID: 2f8da0867883
Revises: 32899e6296d5
Create Date: 2025-05-07 04:16:05.630877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8da0867883'
down_revision = '32899e6296d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
