"""empty message

Revision ID: 32899e6296d5
Revises: 7e418f1bb783
Create Date: 2025-05-07 04:13:34.614381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32899e6296d5'
down_revision = '7e418f1bb783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
