"""empty message

Revision ID: 49490ca9d576
Revises: 2f8da0867883
Create Date: 2025-05-07 10:30:42.012225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49490ca9d576'
down_revision = '2f8da0867883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
