"""empty message

Revision ID: 4b3400b7f7b2
Revises: e51602e58bc0
Create Date: 2025-05-09 01:32:46.675248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3400b7f7b2'
down_revision = 'e51602e58bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
