"""empty message

Revision ID: 54d9b4bc029d
Revises: 600287244c96
Create Date: 2025-05-08 00:19:09.820504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d9b4bc029d'
down_revision = '600287244c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('infructure', sa.Boolean(), nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('cautions_presentees', sa.Boolean(), nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('annulation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'annulation')
    op.drop_column('consultation_fournisseurs', 'cautions_presentees')
    op.drop_column('consultation_fournisseurs', 'infructure')
    # ### end Alembic commands ###
