"""empty message

Revision ID: 5a2c2d773fba
Revises: 9ae2267404d4
Create Date: 2025-04-27 18:17:34.443534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2c2d773fba'
down_revision = '9ae2267404d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
