"""empty message

Revision ID: 5e61184215f7
Revises: 5a2c2d773fba
Create Date: 2025-04-27 19:00:04.270667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e61184215f7'
down_revision = '5a2c2d773fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
