"""empty message

Revision ID: 600287244c96
Revises: 65c48948ae77
Create Date: 2025-05-07 18:45:32.911541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600287244c96'
down_revision = '65c48948ae77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('date_ouverture', sa.DateTime(), nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('pv_ouverture', sa.LargeBinary(), nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('pv_ouverture_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'pv_ouverture_filename')
    op.drop_column('consultation_fournisseurs', 'pv_ouverture')
    op.drop_column('consultation_fournisseurs', 'date_ouverture')
    # ### end Alembic commands ###
