"""empty message

Revision ID: 6083bd6a6d38
Revises: 4e75fd38571d
Create Date: 2025-05-02 04:00:10.298198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6083bd6a6d38'
down_revision = '4e75fd38571d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marches', 'pv_cspmp_lancement_filename')
    op.drop_column('marches', 'date_reunion_demarrage')
    op.drop_column('marches', 'pv_cspmp_lancement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marches', sa.Column('pv_cspmp_lancement', sa.BLOB(), nullable=True))
    op.add_column('marches', sa.Column('date_reunion_demarrage', sa.DATE(), nullable=True))
    op.add_column('marches', sa.Column('pv_cspmp_lancement_filename', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
