"""empty message

Revision ID: 65c48948ae77
Revises: c115abec173e
Create Date: 2025-05-07 11:29:47.664525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c48948ae77'
down_revision = 'c115abec173e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
