"""empty message

Revision ID: 67112ef870f1
Revises: d108f2e0da62
Create Date: 2025-05-10 01:14:51.987757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67112ef870f1'
down_revision = 'd108f2e0da62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
