"""empty message

Revision ID: 6995b99b05ab
Revises: cccbc7c93c36
Create Date: 2025-05-02 23:15:17.442055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6995b99b05ab'
down_revision = 'cccbc7c93c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('nnumero_rfq', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'nnumero_rfq')
    # ### end Alembic commands ###
