"""empty message

Revision ID: 6db096319b7d
Revises: 6995b99b05ab
Create Date: 2025-05-02 23:21:28.418281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db096319b7d'
down_revision = '6995b99b05ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
