"""empty message

Revision ID: 777300370f78
Revises: d8ecb84298cf
Create Date: 2025-05-09 11:22:33.475423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777300370f78'
down_revision = 'd8ecb84298cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marches', sa.Column('cautions_soumission', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marches', 'cautions_soumission')
    # ### end Alembic commands ###
