"""empty message

Revision ID: 7798cb67b6a4
Revises: ff9bf2f394e5
Create Date: 2025-05-11 16:09:12.522104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7798cb67b6a4'
down_revision = 'ff9bf2f394e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
