"""empty message

Revision ID: 7a0f54ab0a4c
Revises: 67112ef870f1
Create Date: 2025-05-11 13:22:49.332059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a0f54ab0a4c'
down_revision = '67112ef870f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cautions', sa.Column('is_fournie', sa.Boolean(), nullable=True))
    op.alter_column('cautions', 'caution_pdf',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('cautions', 'caution_pdf_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cautions', 'caution_pdf_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cautions', 'caution_pdf',
               existing_type=sa.BLOB(),
               nullable=False)
    op.drop_column('cautions', 'is_fournie')
    # ### end Alembic commands ###
