"""empty message

Revision ID: 7c88cb40d00c
Revises: 865bc18b2877
Create Date: 2025-05-08 22:37:43.544032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c88cb40d00c'
down_revision = '865bc18b2877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributions_marches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('offre_technique', sa.LargeBinary(), nullable=True),
    sa.Column('offre_technique_filename', sa.String(length=255), nullable=True),
    sa.Column('offre_financiere', sa.LargeBinary(), nullable=True),
    sa.Column('offre_financiere_filename', sa.String(length=255), nullable=True),
    sa.Column('caution_bonne_execution', sa.LargeBinary(), nullable=True),
    sa.Column('caution_bonne_execution_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attributions_marches')
    # ### end Alembic commands ###
