"""empty message

Revision ID: 7e292217fab4
Revises: f68d09d13e31
Create Date: 2025-05-05 17:06:05.098164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e292217fab4'
down_revision = 'f68d09d13e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
