"""empty message

Revision ID: 7e418f1bb783
Revises: 811b6ae12024
Create Date: 2025-05-05 18:15:04.178745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e418f1bb783'
down_revision = '811b6ae12024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
