"""empty message

Revision ID: 811b6ae12024
Revises: 89f29c2fe28a
Create Date: 2025-05-05 18:12:48.200107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811b6ae12024'
down_revision = '89f29c2fe28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
