"""empty message

Revision ID: 865bc18b2877
Revises: 8843c4ced4be
Create Date: 2025-05-08 09:24:25.266513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '865bc18b2877'
down_revision = '8843c4ced4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'decision_cspmp')
    op.drop_column('consultation_fournisseurs', 'cloture')
    op.drop_column('marche_produit', 'decision_cspmp')
    op.drop_column('marche_produit', 'cloture')
    op.add_column('marches', sa.Column('cloture', sa.Boolean(), nullable=True))
    op.add_column('marches', sa.Column('decision_cspmp', sa.Enum('INFRUCTUEUX', 'NOUVELLE_PROCEDURE', 'GENERER_CONTRATS', name='decisioncspmpenum'), nullable=True))
    op.add_column('marches', sa.Column('contrat', sa.Boolean(), nullable=True))
    op.add_column('marches', sa.Column('numerotation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marches', 'numerotation')
    op.drop_column('marches', 'contrat')
    op.drop_column('marches', 'decision_cspmp')
    op.drop_column('marches', 'cloture')
    op.add_column('marche_produit', sa.Column('cloture', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('marche_produit', sa.Column('decision_cspmp', mysql.ENUM('INFRUCTUEUX', 'NOUVELLE_PROCEDURE', 'GENERER_CONTRATS'), nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('cloture', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('decision_cspmp', mysql.ENUM('INFRUCTUEUX', 'NOUVELLE_PROCEDURE', 'GENERER_CONTRATS'), nullable=True))
    # ### end Alembic commands ###
