"""empty message

Revision ID: 8843c4ced4be
Revises: b8c70ad3c9b2
Create Date: 2025-05-08 09:22:03.239817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8843c4ced4be'
down_revision = 'b8c70ad3c9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'pv_attribution')
    op.drop_column('consultation_fournisseurs', 'pv_attribution_filename')
    op.drop_column('consultation_fournisseurs', 'cautions_presentees')
    op.drop_column('consultation_fournisseurs', 'annulation')
    op.add_column('marche_produit', sa.Column('cloture', sa.Boolean(), nullable=True))
    op.add_column('marche_produit', sa.Column('decision_cspmp', sa.Enum('INFRUCTUEUX', 'NOUVELLE_PROCEDURE', 'GENERER_CONTRATS', name='decisioncspmpenum'), nullable=True))
    op.add_column('marches', sa.Column('cautions_presentees', sa.Boolean(), nullable=True))
    op.add_column('marches', sa.Column('annulation', sa.Boolean(), nullable=True))
    op.add_column('marches', sa.Column('pv_attribution', sa.LargeBinary(), nullable=True))
    op.add_column('marches', sa.Column('pv_attribution_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marches', 'pv_attribution_filename')
    op.drop_column('marches', 'pv_attribution')
    op.drop_column('marches', 'annulation')
    op.drop_column('marches', 'cautions_presentees')
    op.drop_column('marche_produit', 'decision_cspmp')
    op.drop_column('marche_produit', 'cloture')
    op.add_column('consultation_fournisseurs', sa.Column('annulation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('cautions_presentees', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('pv_attribution_filename', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('pv_attribution', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
