"""empty message

Revision ID: 89f29c2fe28a
Revises: 7e292217fab4
Create Date: 2025-05-05 18:05:48.729233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f29c2fe28a'
down_revision = '7e292217fab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
