"""empty message

Revision ID: 932f5cc25546
Revises: a347884696d3
Create Date: 2025-05-05 00:56:50.011392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932f5cc25546'
down_revision = 'a347884696d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marche_produit', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('marche_produit', sa.Column('quantite', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marche_produit', 'quantite')
    op.drop_column('marche_produit', 'id')
    # ### end Alembic commands ###
