"""Add trader and list_noire fields to Fournisseurca

Revision ID: 9ae2267404d4
Revises: a8aee3aeb200
Create Date: 2025-04-26 02:52:57.665617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ae2267404d4'
down_revision = 'a8aee3aeb200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fournisseurs', sa.Column('trader', sa.Boolean(), nullable=True))
    op.add_column('fournisseurs', sa.Column('list_noire', sa.Boolean(), nullable=True))
    op.alter_column('fournisseurs', 'sigle_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fournisseurs', 'sigle_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('fournisseurs', 'list_noire')
    op.drop_column('fournisseurs', 'trader')
    # ### end Alembic commands ###
