"""empty message

Revision ID: a347884696d3
Revises: e9c8694759b0
Create Date: 2025-05-03 01:37:22.480944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a347884696d3'
down_revision = 'e9c8694759b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('date_lancement', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'date_lancement')
    # ### end Alembic commands ###
