"""empty message

Revision ID: a8aee3aeb200
Revises: 27979ef41132
Create Date: 2025-04-26 02:43:36.155136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8aee3aeb200'
down_revision = '27979ef41132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
