"""Initial migration

Revision ID: b75b48388be2
Revises: 
Create Date: 2025-04-24 02:52:27.221275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75b48388be2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fournisseurs', sa.Column('contact', sa.String(length=100), nullable=True))
    op.add_column('fournisseurs', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fournisseurs', 'address')
    op.drop_column('fournisseurs', 'contact')
    # ### end Alembic commands ###
