"""empty message

Revision ID: b8c70ad3c9b2
Revises: 54d9b4bc029d
Create Date: 2025-05-08 09:12:58.230988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c70ad3c9b2'
down_revision = '54d9b4bc029d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('pv_attribution', sa.LargeBinary(), nullable=True))
    op.add_column('consultation_fournisseurs', sa.Column('pv_attribution_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'pv_attribution_filename')
    op.drop_column('consultation_fournisseurs', 'pv_attribution')
    # ### end Alembic commands ###
