"""empty message

Revision ID: ba1a223109ce
Revises: 01e593c210a7
Create Date: 2025-05-12 04:21:05.373021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba1a223109ce'
down_revision = '01e593c210a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offres_financieres', 'unite_monetaire',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offres_financieres', 'unite_monetaire',
               existing_type=sa.String(length=255),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
