"""empty message

Revision ID: c115abec173e
Revises: 49490ca9d576
Create Date: 2025-05-07 11:22:29.969956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c115abec173e'
down_revision = '49490ca9d576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
