"""empty message

Revision ID: c799dc8d872f
Revises: 8c2ed8f385ed
Create Date: 2025-04-28 00:33:40.244616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c799dc8d872f'
down_revision = '8c2ed8f385ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fournisseurs', sa.Column('NIF', sa.String(length=50), nullable=False))
    op.add_column('fournisseurs', sa.Column('etiquettes', sa.JSON(), nullable=True))
    op.drop_column('fournisseurs', 'numero')
    op.add_column('produits', sa.Column('prix_achat', sa.Float(), nullable=False))
    op.add_column('produits', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('produits', sa.Column('peut_etre_vendu', sa.Boolean(), nullable=True))
    op.drop_column('produits', 'prix')
    op.drop_column('produits', 'disponible')
    op.drop_column('produits', 'quantite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('quantite', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('produits', sa.Column('disponible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('produits', sa.Column('prix', mysql.FLOAT(), nullable=False))
    op.drop_column('produits', 'peut_etre_vendu')
    op.drop_column('produits', 'stock')
    op.drop_column('produits', 'prix_achat')
    op.add_column('fournisseurs', sa.Column('numero', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('fournisseurs', 'etiquettes')
    op.drop_column('fournisseurs', 'NIF')
    # ### end Alembic commands ###
