"""empty message

Revision ID: cccbc7c93c36
Revises: 6083bd6a6d38
Create Date: 2025-05-02 11:18:24.865194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccbc7c93c36'
down_revision = '6083bd6a6d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('statut', sa.Enum('OUVERT', 'EVALUE', 'ATTRIBUE', 'INFRUCTUEUSE', 'RESILIE', name='statutenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_fournisseurs', 'statut')
    # ### end Alembic commands ###
