"""empty message

Revision ID: d108f2e0da62
Revises: 777300370f78
Create Date: 2025-05-10 01:13:38.539809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd108f2e0da62'
down_revision = '777300370f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soumissions', 'soumission_document',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('soumissions', 'soumission_document_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soumissions', 'soumission_document_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('soumissions', 'soumission_document',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###
