"""empty message

Revision ID: d8ecb84298cf
Revises: 4b3400b7f7b2
Create Date: 2025-05-09 01:45:32.290800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8ecb84298cf'
down_revision = '4b3400b7f7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultation_fournisseurs', 'statut',
               existing_type=mysql.ENUM('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCTUEUSE', 'ATTRIBUEPROVIS', 'APPROBATIONCNCMP', 'TTRIBUDEFINITIVE', 'NUMEROTATION', 'CONTRAT', 'RESILIE'),
               type_=sa.Enum('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCTUEUSE', 'ATTRIBUEPROVIS', 'ATTRIBUDEFINITIVE', 'APPROBATIONCNCMP', 'NUMEROTATION', 'CONTRAT', 'RESILIE', name='statutenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'PREPARATION'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultation_fournisseurs', 'statut',
               existing_type=sa.Enum('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCTUEUSE', 'ATTRIBUEPROVIS', 'ATTRIBUDEFINITIVE', 'APPROBATIONCNCMP', 'NUMEROTATION', 'CONTRAT', 'RESILIE', name='statutenum'),
               type_=mysql.ENUM('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCTUEUSE', 'ATTRIBUEPROVIS', 'APPROBATIONCNCMP', 'TTRIBUDEFINITIVE', 'NUMEROTATION', 'CONTRAT', 'RESILIE'),
               existing_nullable=False,
               existing_server_default=sa.text("'PREPARATION'"))
    # ### end Alembic commands ###
