"""empty message

Revision ID: e51602e58bc0
Revises: 7c88cb40d00c
Create Date: 2025-05-08 23:58:40.075376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e51602e58bc0'
down_revision = '7c88cb40d00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cautions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_validite', sa.Date(), nullable=True),
    sa.Column('jusqu_a_main_levee', sa.Boolean(), nullable=True),
    sa.Column('caution_pdf', sa.LargeBinary(), nullable=False),
    sa.Column('caution_pdf_filename', sa.String(length=255), nullable=False),
    sa.Column('type_caution', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cautions_bonne_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribution_id'], ['attributions_marches.id'], ),
    sa.ForeignKeyConstraint(['id'], ['cautions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cautions_soumissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soumission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cautions.id'], ),
    sa.ForeignKeyConstraint(['soumission_id'], ['soumissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('consultation_fournisseurs', 'statut',
               existing_type=mysql.ENUM('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCUTEUSE', 'ATTRIBUEPROVIS', 'ATTRIBUDEFINITIVE', 'NUMEROTATION', 'CONTRAT', 'RESILIE'),
               type_=sa.Enum('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCTUEUSE', 'ATTRIBUEPROVIS', 'APPROBATIONCNCMP', 'NUMEROTATION', 'CONTRAT', 'RESILIE', name='statutenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'PREPARATION'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultation_fournisseurs', 'statut',
               existing_type=sa.Enum('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCTUEUSE', 'ATTRIBUEPROVIS', 'APPROBATIONCNCMP', 'NUMEROTATION', 'CONTRAT', 'RESILIE', name='statutenum'),
               type_=mysql.ENUM('PREPARATION', 'LANCE', 'OUVERT', 'EVALUE', 'INFRUCUTEUSE', 'ATTRIBUEPROVIS', 'ATTRIBUDEFINITIVE', 'NUMEROTATION', 'CONTRAT', 'RESILIE'),
               existing_nullable=False,
               existing_server_default=sa.text("'PREPARATION'"))
    op.drop_table('cautions_soumissions')
    op.drop_table('cautions_bonne_execution')
    op.drop_table('cautions')
    # ### end Alembic commands ###
