"""empty message

Revision ID: e603049301b5
Revises: ba1a223109ce
Create Date: 2025-05-14 01:23:42.908957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e603049301b5'
down_revision = 'ba1a223109ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marche_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('offres_financieres', 'unite_monetaire',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offres_financieres', 'unite_monetaire',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('marche_parts')
    # ### end Alembic commands ###
