"""Initial migration

Revision ID: e89a32387ae8
Revises: b75b48388be2
Create Date: 2025-04-24 02:53:23.984321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89a32387ae8'
down_revision = 'b75b48388be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
