"""empty message

Revision ID: e9c8694759b0
Revises: fe55efaa1b6f
Create Date: 2025-05-03 01:16:01.207865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c8694759b0'
down_revision = 'fe55efaa1b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultation_fournisseurs', 'date_limite_depot',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('consultation_fournisseurs', 'date_evaluation',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('consultation_fournisseurs', 'date_lancement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('date_lancement', sa.DATE(), nullable=True))
    op.alter_column('consultation_fournisseurs', 'date_evaluation',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('consultation_fournisseurs', 'date_limite_depot',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
