"""empty message

Revision ID: f68d09d13e31
Revises: 932f5cc25546
Create Date: 2025-05-05 01:26:09.793285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68d09d13e31'
down_revision = '932f5cc25546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offres_financieres', sa.Column('prix_total', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offres_financieres', 'prix_total')
    # ### end Alembic commands ###
