"""empty message

Revision ID: fe55efaa1b6f
Revises: 6db096319b7d
Create Date: 2025-05-02 23:21:42.448201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe55efaa1b6f'
down_revision = '6db096319b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('numero_rfq', sa.String(length=255), nullable=True))
    op.drop_column('consultation_fournisseurs', 'nnumero_rfq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultation_fournisseurs', sa.Column('nnumero_rfq', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('consultation_fournisseurs', 'numero_rfq')
    # ### end Alembic commands ###
