"""empty message

Revision ID: ff9bf2f394e5
Revises: b86fd92b955f
Create Date: 2025-05-11 13:35:11.981030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9bf2f394e5'
down_revision = 'b86fd92b955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offres_financieres', sa.Column('qte', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offres_financieres', 'qte')
    # ### end Alembic commands ###
